apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: user00-wf-input-parameters-
spec:
  entrypoint: dag-template
  arguments:
    parameters:
    - name: message1
      value: Task 1 is executed
    - name: message2
      value: Task2 is executed
    - name: message3
      value: Task3 is executed
    - name: message4
      value: That's it with task 4
  templates:
  - name: dag-template
    inputs:
      parameters:
      - name: message1
      - name: message2
      - name: message3
      - name: message4
    dag:
      tasks:
      - name: task1
        arguments:
          parameters: [{name: text, value: "{{inputs.parameters.message1}}"}]
        template: task-template
      - name: task2
        arguments:
          parameters: [{name: text, value: "{{inputs.parameters.message2}}"}]
        template: task-template
        dependencies: [task1]
      - name: task3
        arguments:
          parameters: [{name: text, value: "{{inputs.parameters.message3}}"}]
        template: task-template
        dependencies: [task1]
      - name: task4
        arguments:
          parameters: [{name: text, value: "{{inputs.parameters.message4}}"}]
        template: task-template
        dependencies: [task2, task3]

  - name: task-template
    inputs:
      parameters:
      - name: text
    script:
      image: python:3.8-slim
      command: [python]
      source: |
        param = "{{inputs.parameters.text}}"
        print(param)

        