apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata: 
  name: archive-location-
spec: 
  entrypoint: hello 
  templates: 
    - name: hello 
      container: 
        image: docker/whalesay 
        command: [cowsay]
        args: ["Hello World..."]
      archiveLocation: 
        archiveLogs: true 
        