apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: workflow-template-hello
spec: 
  entrypoint: hello-template 
  arguments:
    parameters: 
      - name: message 
        value: "from workflow"
  workflowTemplateRef:
    name: workflow-template-ws 
  