apiVersion: v1
data:
  service.email.gmail: '{ username: $email-username, password: $email-password, host:
    smtp.gmail.com, port: 465, from: $email-username }'
  service.slack: |
    token: $slack-token
  template.app-sync-failed: |
    message: |
      Application {{.app.metadata.name}} sync is {{.app.status.sync.status}}.
      Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
    slack:
      attachments: |
        [{
          "title": "{{.app.metadata.name}}",
          "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
          "color": "#ff0000",
          "fields": [{
            "title": "Sync Status",
            "value": "{{.app.status.sync.status}}",
            "short": true
          }, {
            "title": "Repository",
            "value": "{{.app.spec.source.repoURL}}",
            "short": true
          }]
        }]
      # Aggregate the messages to the thread by git commit hash
      groupingKey: "{{.app.status.sync.revision}}"
      notifyBroadcast: true
  template.app-sync-status: |
    message: |
      Application {{.app.metadata.name}} sync is {{.app.status.sync.status}}.
      Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.
    slack:
      attachments: |
        [{
          "title": "{{.app.metadata.name}}",
          "title_link": "{{.context.argocdUrl}}/applications/{{.app.metadata.name}}",
          "color": "#18be52",
          "fields": [{
            "title": "Sync Status 2",
            "value": "{{.app.status.sync.status}}",
            "short": true
          }, {
            "title": "Repository",
            "value": "{{.app.spec.source.repoURL}}",
            "short": true
          }]
        }]
      # Aggregate the messages to the thread by git commit hash
      groupingKey: "{{.app.status.sync.revision}}"
      notifyBroadcast: false
  template.app-sync-succeeded: "message: |\n  {{if eq .serviceType \"slack\"}}:white_check_mark:{{end}}
    Application {{.app.metadata.name}} has been successfully synced at {{.app.status.operationState.finishedAt}}.\n
    \ Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true
    .\nslack:\n  attachments: |\n    [{  \n      \"title\": \"{{ .app.metadata.name}}\",\n
    \     \"title_link\":\"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}\",
    \ \n      \"color\": \"#18be52\",\n      \"fields\": [{\n          \"title\":
    \"Sync Status 1\",    \n          \"value\": \"{{.app.status.sync.status}}\",\n
    \         \"short\": true  \n        }, {    \n          \"title\": \"Repository\",\n
    \         \"value\": \"{{.app.spec.source.repoURL}}\",    \n          \"short\":
    true\n        }  \n        {{range $index, $c := .app.status.conditions}}  \n
    \         {{if not $index}},{{end}}\n            {{if $index}},{{end}}\n              {
    \   \n                 \"title\": \"{{$c.type}}\",\n                 \"value\":
    \"{{$c.message}}\",\n                 \"short\": true\n              }  \n           {{end}}
    \ \n      ]\n    }]\n"
  trigger.on-deployed: |
    when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
    oncePer: app.status.sync.revision
    send: [app-sync-succeeded]
  trigger.on-sync-status-unknown: |
    - when: app.status.sync.status == 'Unknown'     # trigger condition
      send: [app-sync-status, github-commit-status] # template names
  trigger.on-sync-succeeded: |
    - description: Application syncing has succeeded
      send:
      - app-sync-succeeded
      when: app.status.operationState.phase in ['Succeeded']
  trigger.sync-operation-change: |
    - when: app.status.operationState.phase in ['Error', 'Failed'] # `in` も使える
      send: [app-sync-failed, github-commit-status]
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"service.slack":"token: $slack-token\n","template.app-sync-failed":"message: |\n  Application {{.app.metadata.name}} sync is {{.app.status.sync.status}}.\n  Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.\nslack:\n  attachments: |\n    [{\n      \"title\": \"{{.app.metadata.name}}\",\n      \"title_link\": \"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}\",\n      \"color\": \"#ff0000\",\n      \"fields\": [{\n        \"title\": \"Sync Status\",\n        \"value\": \"{{.app.status.sync.status}}\",\n        \"short\": true\n      }, {\n        \"title\": \"Repository\",\n        \"value\": \"{{.app.spec.source.repoURL}}\",\n        \"short\": true\n      }]\n    }]\n  # Aggregate the messages to the thread by git commit hash\n  groupingKey: \"{{.app.status.sync.revision}}\"\n  notifyBroadcast: true\n","template.app-sync-status":"message: |\n  Application {{.app.metadata.name}} sync is {{.app.status.sync.status}}.\n  Application details: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}.\nslack:\n  attachments: |\n    [{\n      \"title\": \"{{.app.metadata.name}}\",\n      \"title_link\": \"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}\",\n      \"color\": \"#18be52\",\n      \"fields\": [{\n        \"title\": \"Sync Status 2\",\n        \"value\": \"{{.app.status.sync.status}}\",\n        \"short\": true\n      }, {\n        \"title\": \"Repository\",\n        \"value\": \"{{.app.spec.source.repoURL}}\",\n        \"short\": true\n      }]\n    }]\n  # Aggregate the messages to the thread by git commit hash\n  groupingKey: \"{{.app.status.sync.revision}}\"\n  notifyBroadcast: false\n","template.app-sync-succeeded":"message: |\n  {{if eq .serviceType \"slack\"}}:white_check_mark:{{end}} Application {{.app.metadata.name}} has been successfully synced at {{.app.status.operationState.finishedAt}}.\n  Sync operation details are available at: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}?operation=true .\nslack:\n  attachments: |\n    [{  \n      \"title\": \"{{ .app.metadata.name}}\",\n      \"title_link\":\"{{.context.argocdUrl}}/applications/{{.app.metadata.name}}\",  \n      \"color\": \"#18be52\",\n      \"fields\": [{\n          \"title\": \"Sync Status 1\",    \n          \"value\": \"{{.app.status.sync.status}}\",\n          \"short\": true  \n        }, {    \n          \"title\": \"Repository\",\n          \"value\": \"{{.app.spec.source.repoURL}}\",    \n          \"short\": true\n        }  \n        {{range $index, $c := .app.status.conditions}}  \n          {{if not $index}},{{end}}\n            {{if $index}},{{end}}\n              {    \n                 \"title\": \"{{$c.type}}\",\n                 \"value\": \"{{$c.message}}\",\n                 \"short\": true\n              }  \n           {{end}}  \n      ]\n    }]\n","trigger.on-sync-succeeded":"- description: Application syncing has succeeded\n  send:\n  - app-sync-succeeded\n  when: app.status.operationState.phase in ['Succeeded']\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"argocd-notifications-cm","namespace":"argocd"}}
  creationTimestamp: "2022-10-14T04:54:48Z"
  name: argocd-notifications-cm
  namespace: argocd
  resourceVersion: "59527"
  uid: a395325c-35bb-4b5a-822a-b7f25e3cd81d
