apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-app
spec:
  destination:
    name: in-cluster
    namespace: guestbook
  project: default
  source:
    path: guestbook
    repoURL: https://
    targetRevision: master
  syncPolicy:
    automated: {}