apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: user00-wf-suspend-
spec:
  entrypoint: steps-template-parallel
  templates:
  - name: steps-template-parallel
    steps:
    - - name: step1
        template: task-template
    - - name: step2
        template: task-template
      - name: step3
        template: task-template
    - - name: delay
        template: delay-template
    - - name: step4
        template: task-template
  - name: task-template
    script:
      image: python:3.8-slim
      command: [python]
      source: |
        print("Task executed.")
  - name: delay-template
    suspend:
      duration: "30s"

      