apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: user00-wf-resource-
spec:
  entrypoint: resource-template
  templates:
  - name: resource-template
    resource:
      action: create
      manifest: |
        apiVersion: argoproj.io/v1alpha1
        kind: Workflow
        metadata:
          generateName: user00-resource-template-
        spec:
          entrypoint: test-template
          templates:
          - name: test-template
            script:
              image: python:3.8-slim
              command: [python]
              source: |
                print("Workflow resource-template created with resource.")
              
