apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: arguments-parameters-from-configmap-
spec: 
  serviceAccountName: argo 
  entrypoint: main 
  templates: 
    - name: main 
      inputs: 
        parameters: 
          - name: message 
            valueFrom: 
              configMapKeyRef: 
                name: simple-parameters 
                key: msg
      container: 
        image: argoproj/argosay:v2 
        args: ["echo", "{{inputs.parameters.message}}"]