apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: cron-wf
spec: 
  schedule: "* * * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 0
  workflowSpec:
    entrypoint: hello 
    templates:
      - name: hello 
        container: 
          image: alphine:3.6 
          command: [sh, -c]
          args: ["
            date;
            sleep 90"
          "]