apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: user00-kustomize-app 
  namespace: argocd
spec: 
  destination:
    namespace: user00
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: kustomize-guestbook 
    repoURL: "https://github.com/yoonjk/argocd-demo.git"
    targetRevision: master 
  syncPolicy:
    automated: {}

    

