apiVersion: v1 
kind: Secret 
metadata: 
  name: user00-private-repo-ssh
  namespace: argocd 
  labels: 
    argocd.argoproj.io/secret-type: repository
stringData: 
  type: git 
  url: git@github.com:yoonjk/argocd-demo-private.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
      :
    PW4wC93Gr5MAAAARbmV4d2ViMUBnbWFpbC5jb20BAg==
    -----END OPENSSH PRIVATE KEY-----

