apiVersion: argoproj.io/v1alpha1 
kind: AppProject 
metadata: 
  name: user00-dev-project
  namespace: argocd 
spec: 
  description: bootcamp description
  sourceRepos:
  - "*"
  destinations: 
  - server: "*"
    namespace: "dev"
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"
  namespaceResourceWhitelist:
  - group: "*"
    kind: "*"