apiVersion: argoproj.io/v1alpha1 
kind: ApplicationSet 
metadata: 
  name: user00-guestbook 
  namespace: argocd
spec: 
  generators: 
  - list: 
      elements:
      - cluster: local-dev-user00 
        url: https://kubernetes.default.svc 
        namespace: dev
      - cluster: staging-user00  
        url: https://kubernetes.default.svc
        namespace: stage 
  template: 
    metadata: 
      name: '{{cluster}}-guestbook'
    spec: 
      project: default 
      source: 
        repoURL: https://github.com/yoonjk/argocd-demo.git 
        targetRevision: master 
        path: guestbook
      destination: 
        server: '{{url}}' 
        namespace: '{{namespace}}'
      syncPolicy: 
        syncOptions: 
        - CreateNamespace=true
        

        