apiVersion: argoproj.io/v1alpha1 
kind: ApplicationSet 
metadata: 
  name: guestbook-1
  namespace: argocd 
spec: 
  generators: 
  - clusters: {}
  template: 
    metadata: 
      name: '{{name}}-guestbook-1'
      namespace: argocd 
    spec: 
      project: default 
      source: 
        repoURL: https://github.com/yoonjk/argocd-demo.git 
        targetRevision: master 
        path: guestbook 
      destination: 
        server: '{{server}}'
        namespace: user00 
      syncPolicy: 
        syncOptions: 
        - CreateNamespace=true