apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset-git-directories
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/yoonjk/argocd-demo
        revision: HEAD
        directories:
          - path: "sample/helm/*"
  template:
    metadata:
      name: '{{`{{path.basename}}`}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/yoonjk/argocd-demo
        path: '{{`{{path}}`}}'
        targetRevision: HEAD
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true