apiVersion: argoproj.io/v1alpha1
kind: Workflow 
metadata: 
  generateName: user00-output-parameter-wf- 
spec: 
  entrypoint: output-parameter 
  templates: 
    - name: output-parameter 
      steps: 
        - - name: generate-parameter 
            template: whalesay 
        - - name: consume-parameter 
            template: print-message 
            arguments: 
              parameters: 
                - name: message 
                  value: "{{steps.generate-parameter.outputs.parameters.hello-param}}"
    - name: whalesay 
      container: 
        image: docker/whalesay:latest 
        command: [sh, -c]
        args: ["
            sleep 1; 
            echo -n hello world > /tmp/hello-world.txt
          "]
      outputs: 
        parameters:
          - name: hello-param 
            valueFrom:
              default: "Foobar" 
              path: /tmp/hello-world.txt 
    - name: print-message
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay:latest
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]

