apiVersion: argoproj.io/v1alpha1 
kind: Workflow 
metadata: 
  generateName: archive-location- 
spec: 
  entrypoint: hello 
  templates: 
    - name: hello 
      container: 
        image: docker/whalesay 
        command: [ cowsay ]
        args: [ "Hi bootcamp"]
      archiveLocation:
        archiveLogs: true