apiVersion: v1
kind: Secret
metadata:
  name: argocd-env-secret
type: Opaque
stringData:
  # choose one of username/password or auth token
  ARGOCD_USERNAME: $ARGOCD_USERNAME
  ARGOCD_PASSWORD: $ARGOCD_PASSWORD
  ARGOCD_AUTH_TOKEN: $TOKEN