apiVersion: argoproj.io/v1alpha1
kind: Workflow 
metadata: 
  generateName: hello-
spec: 
  entrypoint: hello
  templates: 
    - name: hello 
      container: 
        image: alpine
        command: [sh]
        source: |
          #!/bin/sh
          echo "Hello World"