apiVersion: v1
kind: Secret
metadata:
  name: github-credentials
stringData:
  username: nexweb1@gmail.com
  personal_access_token: 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
type: kubernetes.io/basic-auth
