apiVersion: argoproj.io/v1alpha1
kind: Workflow 
metadata: 
  generateName: user00-dag-wf-
spec: 
  entrypoint: dag-template 
  templates: 
    - name: dag-template 
      dag: 
        tasks: 
          - name: task1
            template: task-template 
          - name: task2 
            template: task-template 
            dependencies: [task1]
          - name: task3 
            template: task-template 
            dependencies: [task1]
          - name: task4 
            template: task-template 
            dependencies: [task2, task3]
    - name: task-template 
      script: 
        image: python:3.8-slim 
        command: [python] 
        source: |
          print("Task executed.")

          