apiVersion: v1 
kind: Secret 
metadata: 
  name: local-cluster 
  namespace: argocd
  labels: 
    argocd.argoproj.io/secret-type: cluster 
    environment: "dev"
    provider: "local" 
    non-prod: "true"
type: Opaque
stringData:
  name: local-cluster 
  server: https://kubernetes.default.svc 
  config: |
    { 
      "tlsClientConfig": {
        "insecure": false
      }
    }