apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: kafka
spec:
  eventBusName: default

  dependencies:
    - name: test-dep
      eventSourceName: user00-kafka
      eventName: user00-event 
  triggers:
    - template:
        name: kafka-workflow-trigger
        kafka:
          url: kafka.default:9092
          topic: test
          partition: 0
          payload: 
            - src:
                dependencyName: test-dep
                # dataKey: body
                dataTemplate: "{{ .Input.body | b64dec }}"
              dest: name
