apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: user00-steps-
spec:
  entrypoint: main
  # This spec contains two templates: hello-hello-hello and whalesay
  templates:
    - name: main
      # Instead of just running a container
      # This template has a sequence of steps
      steps:
      - - name: task1  # hello1 is run before the following steps
          template: whalesay
          arguments:
            parameters:
              - name: message
                value: "hello1"
      - - name: task2          # double dash => run after previous step
          template: whalesay
          arguments:
            parameters:
              - name: message
                value: "hello2"
        - name: task3           # single dash => run in parallel with previous step
          template: whalesay
          arguments:
            parameters:
              - name: message
                value: "hello3"
          #  This is the same template as from the previous example
    - name: whalesay
      inputs:
        parameters:
          - name: message
      container: 
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]