apiVersion: argoproj.io/v1alpha1
kind: Workflow 
metadata: 
  generateName: hello-world-
spec: 
  entrypoint: hello
  templates: 
    - name: hello 
      container: 
        image: docker/whalesay
        command: [cowsay]
        args: ["hello world !..."]